# Usa una imagen base de Nginx
FROM nginx:alpine

# Copiar la configuración de Nginx al contenedor
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80 (puerto HTTP)
EXPOSE 80
